In [96]:
import pandas as pd

In [97]:
df_ts = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_total_sales.csv')

In [99]:
df_ts

,Title,Publisher,Developer,Total Sales,Release Date,Last Update,Year
0,PlayerUnknown's Battlegrounds,PUBG Corporation,PUBG Corporation,75000000,2017-12-17,2020-10-24,2017.0
1,PUBG,PUBG Corporation,PUBG Corporation,75000000,2017-12-20,2020-03-16,2017.0
2,Red Dead Redemption 2,Rockstar Games,Rockstar Studios,65000000,2018-10-26,2020-10-08,2018.0
3,Mario Kart 8 Deluxe,Nintendo,Nintendo EPD,62900000,2017-04-28,2018-11-19,2017.0
4,Marvel's Spider-Man,Sony Interactive Entertainment,Insomniac Games,51000000,2018-09-07,2023-01-08,2018.0
...,...,...,...,...,...,...,...
1064,"Guns, Gore & Cannoli",Crazy Monkey,Crazy Monkey Studios,20000,2015-04-30,2018-03-12,2015.0
1065,ToeJam & Earl: Back in the Groove,HumaNature Studios,HumaNature Studios,10000,2019-03-01,2021-09-17,2019.0
1066,Twin Breaker: A Sacred Symbols Adventure,Lillymo Games Inc,Lillymo Games Inc,10000,2020-09-23,2021-02-19,2020.0
1067,Chippy,Facepunch Studios,Facepunch Studios,10000,2019-06-14,2019-12-25,2019.0
1068,Feral Rites,Oculus Studios,Insomniac Games,0,2016-09-13,2023-12-24,2016.0

In [98]:
# Lista de valores en formato de millones
valores = df_ts['Total Sales']

# Convertir a enteros
valores_convertidos = [int(float(valor[:-1]) * 1_000_000) for valor in valores]

df_ts['Total Sales'] = valores_convertidos

TypeError: 'int' object is not subscriptable

In [ ]:
df_ts['Total Sales'] = df_ts['Total Sales'].astype(int)

In [ ]:
df_ts['Total Sales']

0       75000000
1       75000000
2       65000000
3       62900000
4       51000000
          ...
1116       20000
1117       10000
1118       10000
1119       10000
1120           0
Name: Total Sales, Length: 1121, dtype: int64

In [ ]:
df_ts['PAL Sales']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1116   NaN
1117   NaN
1118   NaN
1119   NaN
1120   NaN
Name: PAL Sales, Length: 1121, dtype: float64

In [ ]:
df_ts.columns

Index(['Title', 'Publisher', 'Developer', 'Total Sales', 'NA Sales',
       'PAL Sales', 'Japan Sales', 'Other Sales', 'Release Date',
       'Last Update', 'Year'],
      dtype='object')

In [ ]:
df_ts.drop(columns=['NA Sales','PAL Sales', 'Japan Sales', 'Other Sales'],inplace=True)

In [ ]:
df_ts=df_ts.dropna()

In [ ]:
df_ts['Year'] = df_ts['Year'].astype(str)

In [ ]:
df_ts.to_csv('df11_total_sales1.csv',index=False)

In [ ]:
df_os = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_other_sales.csv')

In [ ]:
# Lista de valores en formato de millones
valores = df_os['Other Sales']

# Convertir a enteros
valores_convertidosos = [int(float(valor[:-1]) * 1_000_000) for valor in valores]

df_os['Other Sales'] = valores_convertidosos

In [ ]:
df_os['Other Sales'] = df_os['Other Sales'].astype(int)

In [ ]:
df_os

,Title,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,Call of Duty: Black Ops 3,Activision,Treyarch,NaN,15.09m,6.18m,6.05m,410000,2015-11-06,2018-01-14,2015.0
1,Red Dead Redemption 2Read the review,Rockstar Games,Rockstar Games,NaN,13.94m,5.26m,6.21m,210000,2018-10-26,2018-11-02,2018.0
2,Call of Duty: WWIIRead the review,Activision,Sledgehammer Games,NaN,13.40m,4.67m,6.21m,400000,2017-11-03,2017-12-31,2017.0
3,FIFA 18,EA Sports,EA Vancouver,NaN,11.80m,1.27m,8.64m,150000,2017-09-29,2018-04-02,2017.0
4,FIFA 17,Electronic Arts,EA Canada,NaN,10.94m,1.26m,7.95m,120000,2016-09-27,2018-03-28,2016.0
...,...,...,...,...,...,...,...,...,...,...,...
1271,Go! Princess PreCure Sugar Oukoku to 6-nin no ...,Bandai Namco Games,Bandai Namco Games,NaN,0.00m,NaN,NaN,0,2015-07-30,2018-08-06,2015.0
1272,Zettai Meikyuu: Himitsu no Oya Yubi Hime,Views,Unknown,NaN,0.00m,NaN,NaN,0,2015-07-30,NaN,2015.0
1273,Natsumegu,Unknown,Unknown,NaN,0.00m,NaN,NaN,0,2015-07-30,NaN,2015.0
1274,Fushigi no Chronicle: Furikaerimasen Katsu Madewa,Spike Chunsoft,Spike Chunsoft,NaN,0.00m,NaN,NaN,0,2015-07-30,2018-09-21,2015.0
1275,Shinsouhan Heart no Kuni no Alice: Wonderful W...,Quinrose,Unknown,NaN,0.00m,NaN,NaN,0,2015-07-30,NaN,2015.0

In [ ]:
df_os.drop(columns=['NA Sales','PAL Sales', 'Japan Sales', 'Total Sales'],inplace=True)

In [ ]:
df_os = df_os.dropna()

In [ ]:
df_os['Year'] = df_os['Year'].astype(str)

/var/folders/zc/6rc7nzhj13scy5qssxw2pjlh0000gn/T/ipykernel_38794/2674589905.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_os['Year'] = df_os['Year'].astype(str)

In [ ]:
df_os.to_csv('df11_other_sales1.csv',index=False)

In [ ]:
df_na = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_na_sales.csv')

In [ ]:
df_na

,Title,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,Call of Duty: Black Ops 3,Activision,Treyarch,NaN,15.09m,6.18m,6.05m,0.41m,2015-11-06,2018-01-14,2015.0
1,Red Dead Redemption 2Read the review,Rockstar Games,Rockstar Games,NaN,13.94m,5.26m,6.21m,0.21m,2018-10-26,2018-11-02,2018.0
2,Call of Duty: WWIIRead the review,Activision,Sledgehammer Games,NaN,13.40m,4.67m,6.21m,0.40m,2017-11-03,2017-12-31,2017.0
3,FIFA 18,EA Sports,EA Vancouver,NaN,11.80m,1.27m,8.64m,0.15m,2017-09-29,2018-04-02,2017.0
4,FIFA 17,Electronic Arts,EA Canada,NaN,10.94m,1.26m,7.95m,0.12m,2016-09-27,2018-03-28,2016.0
...,...,...,...,...,...,...,...,...,...,...,...
2596,Street Fighter 30th Anniversary Collection,Capcom,Capcom,NaN,0.00m,NaN,0.00m,NaN,2018-05-29,2018-11-07,2018.0
2597,Crazy Taxi 3,Unknown,Hitmaker,NaN,0.00m,NaN,0.00m,NaN,2020-12-31,NaN,2020.0
2598,Reveries: SeelenfÃ¤nger,Rondomedia,ERS G-Studio,NaN,0.00m,NaN,0.00m,NaN,2015-10-07,2018-09-22,2015.0
2599,MotoGP 18,Milestone S.r.l.,Milestone S.r.l,NaN,0.00m,NaN,0.00m,NaN,2018-03-31,2019-01-02,2018.0
2600,Zero Time Dilemma,Spike Chunsoft,Unknown,NaN,0.00m,NaN,0.00m,NaN,2016-06-30,NaN,2016.0

In [ ]:
# Lista de valores en formato de millones
valores = df_na['NA Sales']

# Convertir a enteros
valores_convertidosna = [int(float(valor[:-1]) * 1_000_000) for valor in valores]

df_na['NA Sales'] = valores_convertidosna

In [ ]:
df_na['NA Sales'] = df_na['NA Sales'].astype(int)

In [ ]:
df_na.drop(columns=['Other Sales','PAL Sales', 'Japan Sales', 'Total Sales'],inplace=True)

In [ ]:
df_na = df_na.dropna()

In [ ]:
df_na['Year'] = df_na['Year'].astype(str)

/var/folders/zc/6rc7nzhj13scy5qssxw2pjlh0000gn/T/ipykernel_38794/2062740003.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_na['Year'] = df_na['Year'].astype(str)

In [ ]:
df_na.to_csv('df11_na_sales1.csv',index=False)

In [ ]:
df_jap= pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_jap_sales.csv')

In [ ]:
df_jap['Japan Sales']

,Title,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,Call of Duty: Black Ops 3,Activision,Treyarch,NaN,15.09m,6.18m,6.05m,0.41m,2015-11-06,2018-01-14,2015.0
1,Red Dead Redemption 2Read the review,Rockstar Games,Rockstar Games,NaN,13.94m,5.26m,6.21m,0.21m,2018-10-26,2018-11-02,2018.0
2,Call of Duty: WWIIRead the review,Activision,Sledgehammer Games,NaN,13.40m,4.67m,6.21m,0.40m,2017-11-03,2017-12-31,2017.0
3,FIFA 18,EA Sports,EA Vancouver,NaN,11.80m,1.27m,8.64m,0.15m,2017-09-29,2018-04-02,2017.0
4,FIFA 17,Electronic Arts,EA Canada,NaN,10.94m,1.26m,7.95m,0.12m,2016-09-27,2018-03-28,2016.0
...,...,...,...,...,...,...,...,...,...,...,...
1294,Street Fighter 30th Anniversary Collection,Capcom,Capcom,NaN,0.00m,NaN,0.00m,NaN,2018-05-29,2018-11-07,2018.0
1295,Crazy Taxi 3,Unknown,Hitmaker,NaN,0.00m,NaN,0.00m,NaN,2020-12-31,NaN,2020.0
1296,Reveries: SeelenfÃ¤nger,Rondomedia,ERS G-Studio,NaN,0.00m,NaN,0.00m,NaN,2015-10-07,2018-09-22,2015.0
1297,MotoGP 18,Milestone S.r.l.,Milestone S.r.l,NaN,0.00m,NaN,0.00m,NaN,2018-03-31,2019-01-02,2018.0
1298,Zero Time Dilemma,Spike Chunsoft,Unknown,NaN,0.00m,NaN,0.00m,NaN,2016-06-30,NaN,2016.0

In [ ]:
valores = df_jap['Japan Sales']

# Convertir a enteros
valores_convertidosja = [int(float(valor[:-1]) * 1_000_000) for valor in valores]

df_jap['Japan Sales'] = valores_convertidosja

In [ ]:
df_jap['Japan Sales'] = df_jap['Japan Sales'].astype(int)

In [ ]:
df_jap.drop(columns=['Other Sales','PAL Sales', 'NA Sales', 'Total Sales'],inplace=True)

In [ ]:
df_jap = df_jap.dropna()

In [ ]:
df_jap.dtypes

Title            object
Publisher        object
Developer        object
Japan Sales       int64
Release Date     object
Last Update      object
Year            float64
dtype: object

In [ ]:
df_jap['Year'] = df_jap['Year'].astype(str)

/var/folders/zc/6rc7nzhj13scy5qssxw2pjlh0000gn/T/ipykernel_38794/271201322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_jap['Year'] = df_jap['Year'].astype(str)

In [ ]:
df_jap.to_csv('df11_jap_sales1.csv',index=False)

In [ ]:
df_pal = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_pal_sales.csv')

In [ ]:
valores = df_pal['PAL Sales']

# Convertir a enteros
valores_convertidospa = [int(float(valor[:-1]) * 1_000_000) for valor in valores]

df_pal['PAL Sales'] = valores_convertidospa

In [ ]:
df_pal['PAL Sales'] = df_pal['PAL Sales'].astype(int)

In [ ]:
df_pal = df_pal.dropna()

In [ ]:
df_pal.dtypes

Title           object
Publisher       object
Developer       object
PAL Sales        int64
Release Date    object
Last Update     object
Year            object
dtype: object

In [ ]:
df_pal.drop(columns=['Other Sales','Japan Sales', 'NA Sales', 'Total Sales'],inplace=True)

In [ ]:
df_pal['Year'] = df_pal['Year'].astype(str)

In [ ]:
df_pal.to_csv('df11_pal_sales1.csv',index=False)

In [ ]:
df = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_total_sales.csv')

In [ ]:
df

,Title,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,PlayerUnknown's Battlegrounds,PUBG Corporation,PUBG Corporation,75.00m,NaN,NaN,NaN,NaN,2017-12-17,2020-10-24,2017.0
1,PUBG,PUBG Corporation,PUBG Corporation,75.00m,NaN,NaN,NaN,NaN,2017-12-20,2020-03-16,2017.0
2,Red Dead Redemption 2,Rockstar Games,Rockstar Studios,65.00m,NaN,NaN,NaN,NaN,2018-10-26,2020-10-08,2018.0
3,Mario Kart 8 Deluxe,Nintendo,Nintendo EPD,62.90m,NaN,NaN,NaN,NaN,2017-04-28,2018-11-19,2017.0
4,Marvel's Spider-Man,Sony Interactive Entertainment,Insomniac Games,51.00m,NaN,NaN,NaN,NaN,2018-09-07,2023-01-08,2018.0
...,...,...,...,...,...,...,...,...,...,...,...
1116,"Guns, Gore & Cannoli",Crazy Monkey,Crazy Monkey Studios,0.02m,NaN,NaN,NaN,NaN,2015-04-30,2018-03-12,2015.0
1117,ToeJam & Earl: Back in the Groove,HumaNature Studios,HumaNature Studios,0.01m,NaN,NaN,NaN,NaN,2019-03-01,2021-09-17,2019.0
1118,Twin Breaker: A Sacred Symbols Adventure,Lillymo Games Inc,Lillymo Games Inc,0.01m,NaN,NaN,NaN,NaN,2020-09-23,2021-02-19,2020.0
1119,Chippy,Facepunch Studios,Facepunch Studios,0.01m,NaN,NaN,NaN,NaN,2019-06-14,2019-12-25,2019.0
1120,Feral Rites,Oculus Studios,Insomniac Games,0.00m,NaN,NaN,NaN,NaN,2016-09-13,2023-12-24,2016.0

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/ws2_rawg.csv')

In [3]:
df

,id,slug,name,released,tba,background_image,rating,rating_top,ratings,ratings_count,...,dominant_color,platforms,parent_platforms,genres,stores,clip,tags,esrb_rating,short_screenshots,community_rating
0,3498,grand-theft-auto-v,Grand Theft Auto V,2013-09-17,False,https://media.rawg.io/media/games/20a/20aa03a1...,4.47,5,"[{'id': 5, 'title': 'exceptional', 'count': 41...",6856,...,0f0f0f,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action',...","[{'id': 290375, 'store': {'id': 3, 'name': 'Pl...",NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
1,3328,the-witcher-3-wild-hunt,The Witcher 3: Wild Hunt,2015-05-18,False,https://media.rawg.io/media/games/618/618c2031...,4.65,5,"[{'id': 5, 'title': 'exceptional', 'count': 51...",6603,...,0f0f0f,"[{'platform': {'id': 186, 'name': 'Xbox Series...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action',...","[{'id': 354780, 'store': {'id': 5, 'name': 'GO...",NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
2,4200,portal-2,Portal 2,2011-04-18,False,https://media.rawg.io/media/games/2ba/2bac0e87...,4.60,5,"[{'id': 5, 'title': 'exceptional', 'count': 40...",5684,...,0f0f0f,"[{'platform': {'id': 16, 'name': 'PlayStation ...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...","[{'id': 465889, 'store': {'id': 2, 'name': 'Xb...",NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 2, 'name': 'Everyone 10+', 'slug': 'eve...","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
3,4291,counter-strike-global-offensive,Counter-Strike: Global Offensive,2012-08-21,False,https://media.rawg.io/media/games/736/73619bd3...,3.56,4,"[{'id': 4, 'title': 'recommended', 'count': 16...",3479,...,0f0f0f,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 2, 'name': 'Shooter', 'slug': 'shooter...","[{'id': 4619, 'store': {'id': 3, 'name': 'Play...",NaN,"[{'id': 40847, 'name': 'Steam Achievements', '...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
4,5286,tomb-raider,Tomb Raider (2013),2013-03-05,False,https://media.rawg.io/media/games/021/021c4e21...,4.06,4,"[{'id': 4, 'title': 'recommended', 'count': 23...",3896,...,0f0f0f,"[{'platform': {'id': 18, 'name': 'PlayStation ...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action',...","[{'id': 33824, 'store': {'id': 7, 'name': 'Xbo...",NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35595,336822,akash-path-of-the-five,Akash: Path of the Five,2019-06-25,False,https://media.rawg.io/media/screenshots/c62/c6...,0.00,0,"[{'id': 3, 'title': 'meh', 'count': 2, 'percen...",2,...,0f0f0f,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 3, 'name': 'Adventure', 'slug': 'adven...","[{'id': 332336, 'store': {'id': 3, 'name': 'Pl...",NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",0.0
35596,336536,valkyria-chronicles-remaster,Valkyria Chronicles Remaster,2016-02-10,False,https://media.rawg.io/media/screenshots/773/77...,0.00,0,"[{'id': 5, 'title': 'exceptional', 'count': 2,...",3,...,0f0f0f,"[{'platform': {'id': 18, 'name': 'PlayStation ...","[{'platform': {'id': 2, 'name': 'PlayStation',...","[{'id': 10, 'name': 'Strategy', 'slug': 'strat...",[],NaN,[],"{'id': 3, 'name': 'Teen', 'slug': 'teen'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",0.0
35597,334185,inazuma-eleven-3-team-ogre-attacks,Inazuma Eleven 3: Team Ogre Attacks!,2014-02-14,False,NaN,0.00,5,"[{'id': 5, 'title': 'exceptional', 'count': 3,...",5,...,0f0f0f,"[{'platform': {'id': 8, 'name': 'Nintendo 3DS'...","[{'platform': {'id': 7, 'name': 'Nintendo', 's...","[{'id': 15, 'name': 'Sports', 'slug': 'sports'...",[],NaN,[],NaN,[],NaN
35598,333151,digimon-world-re-digitize-decode,Digimon World Re: Digitize,2012-07-19,False,https://media.rawg.io/media/games/e75/e75be445...,4.00,4,"[{'id': 4, 'title': 'recommended', 'count': 4,...",6,...,0f0f0f,"[{'platform': {'id': 17, 'name': 'PSP', 'slug'...","[{'platform': {'id': 2, 'name': 'PlayStation',...","[{'id': 5, 'name': 'RPG', 'slug': 'role-playin...",[],NaN,"[{'id': 72501, 'name': 'fan-translation', 'slu...","{'id': 2, 'name': 'Everyone 10+', 'slug': 'eve...","[{'id': -1, 'image': 'https://media.rawg.io/me...",NaN
35599,333142,diaboliklovers,Diabolik Lovers,2012-10-11,False,https://media.rawg.io/media/screenshots/49b/49...,0.00,0,"[{'id': 4, 'title': 'recommended', 'count': 2,...",3,...,0f0f0f,"[{'platform': {'id': 17, 'name': 'PSP', 'slug'...","[{'platform': {'id': 2, 'name': 'PlayStation',...","[{'id': 3, 'name': 'Adventure', 'slug': 'adven...",[],NaN,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 4, 'name': 'Mature', 'slug': 'mature'}","[{'id': -1, 'image': 'https://media.rawg.io/me...",0.0