In [1]:
import pandas as pd

In [2]:
df_info = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df_info_clean_fin_0_nan_type.csv')

/var/folders/zc/6rc7nzhj13scy5qssxw2pjlh0000gn/T/ipykernel_10496/2147467284.py:1: DtypeWarning: Columns (16,17,18,19,30,31,32,33,34,35,36,37,38,39,40,41,42,49,50,51,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  df_info = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df_info_clean_fin_0_nan_type.csv')

In [3]:
df_info

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,tag50,tag51,tag52,tag53,tag54,tag55,num_tags,num_platforms,total_platform_game_counts,total_games_counts_stores
0,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,0,0,0,0,0,0,19,7,555537,114169
1,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,0,0,0,0,0,0,20,7,659649,126236
2,Portal 2,2011-04-18,4,5,5685,95,2024-08-29 07:23:05,5737,Everyone 10+,'Shooter',...,0,0,0,0,0,0,25,6,728683,112824
3,Counter-Strike: Global Offensive,2012-08-21,3,4,3479,81,2024-08-20 10:48:54,3515,Mature,'Shooter',...,0,0,0,0,0,0,24,4,618464,107959
4,Tomb Raider (2013),2013-03-05,4,4,3896,86,2024-08-25 15:59:03,3925,Mature,'Action',...,0,0,0,0,0,0,17,6,658039,201960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9148,ORBIT,2011-12-06,0,0,0,73,2023-11-04 01:00:08,0,Everyone,'Action',...,0,0,0,0,0,0,27,5,546324,119954
9149,Atari Flashback Classics Vol. 1,2016-10-13,0,0,3,73,2022-09-09 08:34:23,3,Everyone,'Arcade',...,0,0,0,0,0,0,6,2,12463,12826
9150,The Casting of Frank Stone,2024-09-03,0,0,0,73,2024-07-17 07:08:32,0,Mature,'Adventure',...,0,0,0,0,0,0,0,3,537214,112370
9151,Quake II: Enhanced Edition,2023-08-10,4,5,7,73,2024-07-12 08:19:16,7,Adults Only,'Action',...,0,0,0,0,0,0,11,6,555181,105831
9152,Paleo Pines,2023-09-26,0,0,2,73,2023-09-29 09:22:13,1,Everyone,'Adventure',...,0,0,0,0,0,0,20,2,612616,98197

In [4]:
df_ts = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_total_sales.csv')

In [5]:
df_ts

,Title,Publisher,Developer,Total Sales,Release Date,Last Update,Year
0,PlayerUnknown's Battlegrounds,PUBG Corporation,PUBG Corporation,75000000,2017-12-17,2020-10-24,2017.0
1,PUBG,PUBG Corporation,PUBG Corporation,75000000,2017-12-20,2020-03-16,2017.0
2,Red Dead Redemption 2,Rockstar Games,Rockstar Studios,65000000,2018-10-26,2020-10-08,2018.0
3,Mario Kart 8 Deluxe,Nintendo,Nintendo EPD,62900000,2017-04-28,2018-11-19,2017.0
4,Marvel's Spider-Man,Sony Interactive Entertainment,Insomniac Games,51000000,2018-09-07,2023-01-08,2018.0
...,...,...,...,...,...,...,...
1064,"Guns, Gore & Cannoli",Crazy Monkey,Crazy Monkey Studios,20000,2015-04-30,2018-03-12,2015.0
1065,ToeJam & Earl: Back in the Groove,HumaNature Studios,HumaNature Studios,10000,2019-03-01,2021-09-17,2019.0
1066,Twin Breaker: A Sacred Symbols Adventure,Lillymo Games Inc,Lillymo Games Inc,10000,2020-09-23,2021-02-19,2020.0
1067,Chippy,Facepunch Studios,Facepunch Studios,10000,2019-06-14,2019-12-25,2019.0
1068,Feral Rites,Oculus Studios,Insomniac Games,0,2016-09-13,2023-12-24,2016.0

In [6]:
df_ts['name'] = df_ts['Title']
df_ts.drop(columns='Title',inplace=True)

In [9]:
df_ts

,Publisher,Developer,Total Sales,Release Date,Last Update,Year,name
0,PUBG Corporation,PUBG Corporation,75000000,2017-12-17,2020-10-24,2017.0,PlayerUnknown's Battlegrounds
1,PUBG Corporation,PUBG Corporation,75000000,2017-12-20,2020-03-16,2017.0,PUBG
2,Rockstar Games,Rockstar Studios,65000000,2018-10-26,2020-10-08,2018.0,Red Dead Redemption 2
3,Nintendo,Nintendo EPD,62900000,2017-04-28,2018-11-19,2017.0,Mario Kart 8 Deluxe
4,Sony Interactive Entertainment,Insomniac Games,51000000,2018-09-07,2023-01-08,2018.0,Marvel's Spider-Man
...,...,...,...,...,...,...,...
1064,Crazy Monkey,Crazy Monkey Studios,20000,2015-04-30,2018-03-12,2015.0,"Guns, Gore & Cannoli"
1065,HumaNature Studios,HumaNature Studios,10000,2019-03-01,2021-09-17,2019.0,ToeJam & Earl: Back in the Groove
1066,Lillymo Games Inc,Lillymo Games Inc,10000,2020-09-23,2021-02-19,2020.0,Twin Breaker: A Sacred Symbols Adventure
1067,Facepunch Studios,Facepunch Studios,10000,2019-06-14,2019-12-25,2019.0,Chippy
1068,Oculus Studios,Insomniac Games,0,2016-09-13,2023-12-24,2016.0,Feral Rites

In [10]:
df_merge = pd.merge(df_info,df_ts,on='name',how='inner')

In [20]:
df_merge.drop(columns=['Release Date', 'Last Update'],inplace=True)

In [35]:
df_merge.drop(columns=['Year'],inplace=True)

In [36]:
df_merge.to_csv('df_merge_ts_1.csv',index=False)

In [14]:
df_os = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_other_sales.csv')

In [16]:
df_os['name'] = df_os['Title']
df_os.drop(columns='Title',inplace=True)

In [17]:
df_merge2 = pd.merge(df_info,df_os,on='name',how='inner')

In [22]:
df_merge2.drop(columns=['Release Date', 'Last Update'],inplace=True)

In [26]:
df_merge2

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,tag54,tag55,num_tags,num_platforms,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Other Sales,Year
0,The Elder Scrolls V: Skyrim,2011-11-11,4,5,4637,94,2024-08-29 07:37:22,4686,Mature,'Action',...,0,0,24,8,561040,117005,Bethesda Softworks,Bethesda Softworks,60000,2017.0
1,Life is Strange,2015-01-29,4,5,3622,83,2024-08-24 20:04:32,3669,Mature,'Adventure',...,0,0,24,9,865242,211762,Square Enix,DONTNOD Entertainment,50000,2016.0
2,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,0,0,43,6,809651,112253,Activision,Bungie,100000,2017.0
3,Fallout 4,2015-11-09,3,4,3273,84,2024-08-20 17:14:15,3302,Mature,'Action',...,0,0,19,4,548593,110908,Bethesda Softworks,Bethesda Game Studios,270000,2015.0
4,Fallout 4,2015-11-09,3,4,3273,84,2024-08-20 17:14:15,3302,Mature,'Action',...,0,0,19,4,548593,110908,Bethesda Softworks,Bethesda Game Studios,20000,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Super Robot Wars X,2018-03-29,0,0,1,73,2023-05-02 21:50:09,2,Teen,'Strategy',...,0,0,5,2,540361,97921,Bandai Namco Games,Bandai Namco,70000,2018.0
258,Dark Rose Valkyrie,2017-06-06,0,0,1,73,2019-08-02 16:21:22,1,Teen,'RPG',...,0,0,6,1,6825,7961,Idea Factory International,Compile Heart,40000,2017.0
259,Resident Evil: Origins Collection,2016-01-22,3,4,6,73,2019-11-19 18:01:08,6,Mature,'Action',...,0,0,2,4,552920,9046,Capcom,Capcom,70000,2016.0
260,Ultra Street Fighter II: The Final Challengers,2017-05-26,3,4,7,66,2023-03-23 14:50:11,7,Teen,'Action',...,0,0,2,1,5503,9046,Capcom,Capcom,90000,2017.0
261,The Caligula Effect,2016-06-23,0,0,4,61,2023-04-10 09:23:22,4,Teen,'RPG',...,0,0,7,1,1447,0,Atlus,FuRyu,70000,2017.0

In [33]:
df_merge2.drop(columns=['Year'],inplace=True)

In [34]:
df_merge2.to_csv('df_merge_os_1.csv',index=False)

In [24]:
df_jps = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_jap_sales.csv')

In [25]:
df_jps

,Title,Publisher,Developer,Japan Sales,Release Date,Last Update,Year
0,Call of Duty: Black Ops 3,Activision,Treyarch,6050000,2015-11-06,2018-01-14,2015.0
1,Red Dead Redemption 2Read the review,Rockstar Games,Rockstar Games,6210000,2018-10-26,2018-11-02,2018.0
2,Call of Duty: WWIIRead the review,Activision,Sledgehammer Games,6210000,2017-11-03,2017-12-31,2017.0
3,FIFA 18,EA Sports,EA Vancouver,8640000,2017-09-29,2018-04-02,2017.0
4,FIFA 17,Electronic Arts,EA Canada,7950000,2016-09-27,2018-03-28,2016.0
...,...,...,...,...,...,...,...
1175,NASCAR '15,Deep Silver,Eutechnyx,0,2015-05-22,2018-04-14,2015.0
1176,Marvel vs. Capcom: Infinite,Capcom,Capcom,0,2017-09-19,2018-09-22,2017.0
1177,Street Fighter 30th Anniversary Collection,Capcom,Capcom,0,2018-05-29,2018-11-07,2018.0
1178,Reveries: Seelenfänger,Rondomedia,ERS G-Studio,0,2015-10-07,2018-09-22,2015.0
1179,MotoGP 18,Milestone S.r.l.,Milestone S.r.l,0,2018-03-31,2019-01-02,2018.0

In [27]:
df_jps['name'] = df_jps['Title']
df_jps.drop(columns='Title',inplace=True)

In [42]:
df_merge3 = pd.merge(df_info,df_jps,on='name',how='inner')

In [43]:
df_merge3

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,num_tags,num_platforms,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Japan Sales,Release Date,Last Update,Year
0,The Elder Scrolls V: Skyrim,2011-11-11,4,5,4637,94,2024-08-29 07:37:22,4686,Mature,'Action',...,24,8,561040,117005,Bethesda Softworks,Bethesda Softworks,320000,2017-11-17,2018-01-01,2017.0
1,Red Dead Redemption 2,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,33,3,547486,112253,Rockstar Games,Rockstar Games,1470000,2018-10-26,2018-11-02,2018.0
2,Life is Strange,2015-01-29,4,5,3622,83,2024-08-24 20:04:32,3669,Mature,'Adventure',...,24,9,865242,211762,Square Enix,DONTNOD Entertainment,160000,2016-01-19,2018-01-07,2016.0
3,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,43,6,809651,112253,Activision,Bungie,1440000,2017-09-06,2018-04-20,2017.0
4,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,43,6,809651,112253,Activision,Bungie,470000,2017-09-06,2018-04-20,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,50000,2015-10-27,2019-01-19,2015.0
514,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,40000,2015-10-27,2019-01-19,2015.0
515,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,30000,2015-10-27,2019-01-19,2015.0
516,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,10000,2015-10-27,2019-01-19,2015.0
517,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,0,2015-10-27,2019-01-19,2015.0

In [44]:
df_merge3.drop(columns=['Release Date', 'Last Update'],inplace=True)
df_merge3.drop(columns=['Year'],inplace=True)

In [31]:
df_merge3

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,tag54,tag55,num_tags,num_platforms,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Japan Sales,Year
0,The Elder Scrolls V: Skyrim,2011-11-11,4,5,4637,94,2024-08-29 07:37:22,4686,Mature,'Action',...,0,0,24,8,561040,117005,Bethesda Softworks,Bethesda Softworks,320000,2017.0
1,Red Dead Redemption 2,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,0,0,33,3,547486,112253,Rockstar Games,Rockstar Games,1470000,2018.0
2,Life is Strange,2015-01-29,4,5,3622,83,2024-08-24 20:04:32,3669,Mature,'Adventure',...,0,0,24,9,865242,211762,Square Enix,DONTNOD Entertainment,160000,2016.0
3,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,0,0,43,6,809651,112253,Activision,Bungie,1440000,2017.0
4,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,0,0,43,6,809651,112253,Activision,Bungie,470000,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,0,0,4,4,541008,106043,Little Orbit,Torus Games,50000,2015.0
514,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,0,0,4,4,541008,106043,Little Orbit,Torus Games,40000,2015.0
515,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,0,0,4,4,541008,106043,Little Orbit,Torus Games,30000,2015.0
516,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,0,0,4,4,541008,106043,Little Orbit,Torus Games,10000,2015.0
517,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,0,0,4,4,541008,106043,Little Orbit,Torus Games,0,2015.0

In [46]:
df_merge3.to_csv('df_merge_jap.csv',index=False)

In [37]:
df_nas = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df11_na_sales.csv')

In [38]:
df_nas['name'] = df_nas['Title']
df_nas.drop(columns='Title',inplace=True)

In [47]:
df_merge4 = pd.merge(df_info,df_nas,on='name',how='inner')

In [48]:
df_merge4

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,num_tags,num_platforms,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,NA Sales,Release Date,Last Update,Year
0,The Elder Scrolls V: Skyrim,2011-11-11,4,5,4637,94,2024-08-29 07:37:22,4686,Mature,'Action',...,24,8,561040,117005,Bethesda Softworks,Bethesda Softworks,1150000,2017-11-17,2018-01-01,2017.0
1,Red Dead Redemption 2,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,33,3,547486,112253,Rockstar Games,Rockstar Games,5770000,2018-10-26,2018-11-02,2018.0
2,Life is Strange,2015-01-29,4,5,3622,83,2024-08-24 20:04:32,3669,Mature,'Adventure',...,24,9,865242,211762,Square Enix,DONTNOD Entertainment,370000,2016-01-19,2018-01-07,2016.0
3,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,43,6,809651,112253,Activision,Bungie,4139999,2017-09-06,2018-04-20,2017.0
4,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,43,6,809651,112253,Activision,Bungie,2350000,2017-09-06,2018-04-20,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,60000,2015-10-27,2019-01-19,2015.0
768,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,40000,2015-10-27,2019-01-19,2015.0
769,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,30000,2015-10-27,2019-01-19,2015.0
770,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,10000,2015-10-27,2019-01-19,2015.0
771,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,4,4,541008,106043,Little Orbit,Torus Games,0,2015-10-27,2019-01-19,2015.0

In [49]:
df_merge4.drop(columns=['Release Date', 'Last Update'],inplace=True)
df_merge4.drop(columns=['Year'],inplace=True)

In [50]:
df_merge4.to_csv('df_merge_na.csv',index=False)

In [51]:
df_sales_todo = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/data_vg_ws_clean.csv')

In [52]:
df_sales_todo

,Title,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,PlayerUnknown's Battlegrounds,PUBG Corporation,PUBG Corporation,75.00m,NaN,NaN,NaN,NaN,2017-12-17,2020-10-24,2017.0
1,PUBG,PUBG Corporation,PUBG Corporation,75.00m,NaN,NaN,NaN,NaN,2017-12-20,2020-03-16,2017.0
2,Red Dead Redemption 2,Rockstar Games,Rockstar Studios,65.00m,NaN,NaN,NaN,NaN,2018-10-26,2020-10-08,2018.0
3,Mario Kart 8 Deluxe,Nintendo,Nintendo EPD,62.90m,NaN,NaN,NaN,NaN,2017-04-28,2018-11-19,2017.0
4,Marvel's Spider-Man,Sony Interactive Entertainment,Insomniac Games,51.00m,NaN,NaN,NaN,NaN,2018-09-07,2023-01-08,2018.0
...,...,...,...,...,...,...,...,...,...,...,...
8237,Zombieland: Double Tap - Road Trip,GameMill Entertainment,High Voltage Software,NaN,NaN,NaN,NaN,NaN,2019-10-15,2020-09-25,2019.0
8238,Zombillie,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,2018-03-29,2018-03-26,2018.0
8239,Zone of the Enders: The 2nd Runner MARS,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,2018-09-06,2018-09-26,2018.0
8240,Zoo Tycoon: Ultimate Animal Collection,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,2017-10-31,2018-09-26,2017.0
8241,Zoo Tycoon: Ultimate Animal Collection,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,2018-09-14,2018-11-19,2018.0

In [53]:
df_sales_todo['name'] = df_sales_todo['Title']
df_sales_todo.drop(columns='Title',inplace=True)

In [54]:
df_merge_todo = pd.merge(df_info,df_sales_todo, on='name',how='inner')

In [55]:
df_merge_todo

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Year
0,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,Rockstar Games,Rockstar North,12.60m,NaN,NaN,NaN,NaN,2015-04-14,2018-11-02,2015.0
1,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,2021-12-01,2020-06-11,2021.0
2,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,2021-12-01,2020-06-12,2021.0
3,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,50.00m,NaN,NaN,NaN,NaN,2015-05-18,2020-10-29,2015.0
4,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,15.90m,NaN,NaN,NaN,NaN,2015-05-19,2018-05-04,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,Little Orbit,Torus Games,NaN,0.06m,NaN,0.05m,NaN,2015-10-27,2019-01-19,2015.0
2666,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,Little Orbit,Torus Games,NaN,0.04m,NaN,0.04m,NaN,2015-10-27,2019-01-19,2015.0
2667,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,Little Orbit,Torus Games,NaN,0.03m,NaN,0.03m,NaN,2015-10-27,2019-01-19,2015.0
2668,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,Little Orbit,Torus Games,NaN,0.01m,NaN,0.01m,NaN,2015-10-27,2019-01-19,2015.0
2669,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,Little Orbit,Torus Games,NaN,0.00m,NaN,0.00m,NaN,2015-10-27,2019-01-19,2015.0

In [56]:
df_merge_todo.drop(columns=['Release Date', 'Last Update', 'Year'],inplace=True)

In [62]:
df_merge_todo['released'] = pd.to_datetime(df_merge_todo['released'])

In [63]:
df_merge_todo['Year'] = df_merge_todo['released'].dt.year

In [64]:
df_merge_todo['Year'] == 2015 & df_merge_todo['Year'] == 2024

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Year
0,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,555537,114169,Rockstar Games,Rockstar North,12.60m,NaN,NaN,NaN,NaN,2013
1,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,555537,114169,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,2013
2,Grand Theft Auto V,2013-09-17,4,5,6858,92,2024-08-29 07:36:57,6964,Mature,'Action',...,555537,114169,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,2013
3,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,50.00m,NaN,NaN,NaN,NaN,2015
4,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,15.90m,NaN,NaN,NaN,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.06m,NaN,0.05m,NaN,2015
2666,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.04m,NaN,0.04m,NaN,2015
2667,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.03m,NaN,0.03m,NaN,2015
2668,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.01m,NaN,0.01m,NaN,2015
2669,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.00m,NaN,0.00m,NaN,2015

In [74]:
df_con_todo_15_24_1 = df_merge_todo[(df_merge_todo['Year'] >= 2015) & (df_merge_todo['Year'] <= 2024)]

In [75]:
df_con_todo_15_24_1 = df_con_todo_15_24_1.fillna('N/A')

In [77]:
df_con_todo_15_24_1['name'] = df_con_todo_15_24_1['name'].drop_duplicates()

In [79]:
df_con_todo_15_24_1.dropna()

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Year
3,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,50.00m,N/A,N/A,N/A,N/A,2015
7,Red Dead Redemption 2,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,547486,112253,Rockstar Games,Rockstar Studios,65.00m,N/A,N/A,N/A,N/A,2018
10,Life is Strange,2015-01-29,4,5,3622,83,2024-08-24 20:04:32,3669,Mature,'Adventure',...,865242,211762,Square Enix,DONTNOD Entertainment,3.00m,N/A,N/A,N/A,N/A,2015
13,Destiny 2,2017-09-06,3,4,2595,82,2024-08-24 15:16:53,2620,Teen,'Action',...,809651,112253,Activision,Bungie,N/A,4.14m,1.92m,1.44m,0.10m,2017
17,God of War (2018),2018-04-20,4,5,4760,94,2024-08-28 20:15:05,4859,Mature,'Action',...,541848,113670,Sony Interactive Entertainment,SIE Santa Monica Studio,23.52m,N/A,N/A,N/A,N/A,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,Neon City Riders,2020-03-11,0,0,0,73,2020-12-16 14:40:55,0,Everyone 10+,'Action',...,552826,119793,Bromio,Mecha Studios,N/A,N/A,N/A,N/A,N/A,2020
2662,Taiko no Tatsujin: Drum 'n' Fun!,2018-11-02,0,5,4,78,2023-01-26 19:36:51,5,Everyone,'Arcade',...,5503,9046,Bandai Namco Games,Bandai Namco Games,2.24m,N/A,N/A,N/A,N/A,2018
2663,Super One More Jump,2018-01-25,3,4,6,73,2024-05-23 14:03:11,7,Everyone 10+,'Arcade',...,135237,101702,SMG Studio,SMG Studio,N/A,N/A,N/A,N/A,N/A,2018
2664,The Caligula Effect,2016-06-23,0,0,4,61,2023-04-10 09:23:22,4,Teen,'RPG',...,1447,0,Atlus,FuRyu,N/A,0.07m,N/A,N/A,0.07m,2016
2665,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,N/A,0.06m,N/A,0.05m,N/A,2015

In [81]:
df_con_todo_15_24_1.to_csv('df_info_merge_data_vg_ws_clean.csv',index=False)

In [82]:
def convertir_a_millones(valor):
    if isinstance(valor, str) and 'm' in valor:
        return int(float(valor.replace('m', '')) * 1_000_000)
    else:
        return None

cols_to_convert = ['Total Sales', 'NA Sales', 'PAL Sales', 'Japan Sales', 'Other Sales']
for col in cols_to_convert:
    df_con_todo_15_24_1[col] = df_con_todo_15_24_1[col].apply(convertir_a_millones)

In [83]:
df_con_todo_15_24_1

,name,released,rating,rating_top,ratings_count,metacritic,updated,reviews_count,age_rating,genre,...,total_platform_game_counts,total_games_counts_stores,Publisher,Developer,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Year
3,The Witcher 3: Wild Hunt,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,50000000.0,NaN,NaN,NaN,NaN,2015
4,NaN,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,15900000.0,NaN,NaN,NaN,NaN,2015
5,NaN,2015-05-18,4,5,6606,92,2024-08-28 20:12:31,6715,Mature,'Action',...,659649,126236,Warner Bros. Interactive Entertainment,CD Projekt Red Studio,4700000.0,NaN,NaN,NaN,NaN,2015
7,Red Dead Redemption 2,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,547486,112253,Rockstar Games,Rockstar Studios,65000000.0,NaN,NaN,NaN,NaN,2018
8,NaN,2018-10-26,4,5,5006,96,2024-08-27 15:25:00,5119,Mature,'Action',...,547486,112253,Rockstar Games,Rockstar Games,NaN,5770000.0,3760000.0,1470000.0,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,Monster High: New Ghoul in School,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,60000.0,NaN,50000.0,NaN,2015
2666,NaN,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,40000.0,NaN,40000.0,NaN,2015
2667,NaN,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,30000.0,NaN,30000.0,NaN,2015
2668,NaN,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,10000.0,NaN,10000.0,NaN,2015
2669,NaN,2015-11-17,0,0,3,73,2022-07-28 23:39:45,3,Everyone 10+,'Adventure',...,541008,106043,Little Orbit,Torus Games,NaN,0.0,NaN,0.0,NaN,2015

In [84]:
df_con_todo_15_24_1=df_con_todo_15_24_1.fillna('N/A')

In [85]:
df_con_todo_15_24_1.to_csv('df_info_merge_data_vg_ws_clean.csv',index=False)