# Merge dfs

In [1]:
import pandas as pd
import numpy as np
import requests
import os

In [2]:
df_principal = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/df_clean_final.csv')

In [3]:
df_principal

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,rating_top,ratings_count,added,metacritic,suggestions_count,numero_stores
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,5,6855,21102,92.0,434,5
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,5,6598,20584,92.0,677,5
2,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,5,4632,15889,94.0,602,4
3,3,32,Destiny 2,2017-09-06,False,Teen,Shooter,Action,10456.0,6,4,2594,13771,82.0,1230,4
4,4,3070,Fallout 4,2015-11-09,False,Mature,Action,RPG,8543.0,4,4,3273,13480,84.0,460,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,1100,795323,Dead by Daylight - Hellraiser,2021-09-07,False,Mature,Action,no,472.0,6,0,0,0,0.0,394,2
975,1101,812169,SENSEs: Midnight,2022-07-22,False,Teen,Adventure,no,472.0,7,0,0,0,0.0,371,4
976,1103,795327,Dead by Daylight - Spark of Madness,2017-05-11,False,Mature,Adventure,Action,472.0,6,0,0,0,0.0,384,1
977,1104,887670,Pre-purchase Romancing SaGa - Minstrel Song- R...,2022-12-01,False,Mature,RPG,no,472.0,4,0,0,0,0.0,162,2
978,1106,968275,Neo Breakout,2022-11-11,False,Mature,Arcade,no,472.0,3,0,0,0,0.0,0,0

In [12]:
df_reddit_llm_g_b_i = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/reddit_g_b_i.csv')

In [13]:
df_reddit_llm_g_b_i

,game_name,average_percentage_good,average_percentage_intermediate,average_percentage_bad
0,13 Sentinels: Aegis Rim,40.0,60.0,0.0
1,A Plague Tale: Innocence,20.0,40.0,40.0
2,A Plague Tale: Requiem,30.0,30.0,40.0
3,Ace Combat 5: The Unsung War,60.0,20.0,20.0
4,Aeterna Noctis,60.0,30.0,10.0
...,...,...,...,...
208,Weird West,20.0,80.0,0.0
209,World War Z: Aftermath,30.0,40.0,30.0
210,Wreckfest,50.0,30.0,20.0
211,Yakuza: Like a Dragon,40.0,50.0,10.0
212,eFootball 2022,50.0,50.0,0.0

In [37]:
df_kaggle_ventas = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/vgsales.csv')

In [38]:
df_kaggle_ventas

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [80]:
df_kaggle_ventas_2 = pd.read_csv('/Users/Jaimecalderon/Desktop/IRONHACK/Proyectos/Proyecto final/Videojuegos/vgsales 2.csv')

In [81]:
df_kaggle_ventas_2 = df_kaggle_ventas_2.dropna()

In [39]:
df_kaggle_ventas = df_kaggle_ventas.dropna()

In [40]:
df_kaggle_ventas

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

## MErge scores

In [31]:
df_scores_todo = pd.merge(df_principal, df_reddit_llm_g_b_i, on='game_name', how='inner')

In [32]:
df_scores_todo

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,rating_top,ratings_count,added,metacritic,suggestions_count,numero_stores,average_percentage_good,average_percentage_intermediate,average_percentage_bad
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,5,6855,21102,92.0,434,5,10.0,50.0,40.0
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,5,6598,20584,92.0,677,5,30.0,60.0,10.0
2,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,5,4632,15889,94.0,602,4,50.0,40.0,10.0
3,3,32,Destiny 2,2017-09-06,False,Teen,Shooter,Action,10456.0,6,4,2594,13771,82.0,1230,4,40.0,40.0,20.0
4,5,41494,Cyberpunk 2077,2020-12-10,False,Mature,Shooter,"Action, RPG",6495.0,5,5,2654,12805,73.0,623,5,30.0,40.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,923,963591,Fortnite Zero Build: No-Build Battle Royale,2022-03-29,False,Mature,Shooter,Action,2.0,7,0,0,6,0.0,145,1,40.0,20.0,40.0
209,972,982815,F1 Manager 2024,2024-07-23,False,Everyone,Racing,"Strategy, Simulation",2.0,5,0,0,3,0.0,98,3,40.0,60.0,0.0
210,981,975453,Rocket Racing,2023-12-08,False,Mature,Racing,no,2.0,7,0,1,3,0.0,177,2,30.0,40.0,30.0
211,995,965121,Hammerwatch II: Anniversary Pack,2023-08-15,False,Teen,Indie,"Adventure, Action, RPG",3.0,6,0,0,3,0.0,239,1,30.0,30.0,40.0
212,1036,977220,Fortnite Festival,2023-12-09,False,Mature,Arcade,Action,472.0,7,0,1,2,0.0,351,0,40.0,30.0,30.0

In [41]:
df_kaggle_ventas.rename(columns={'Name':'game_name'}, inplace=True)

/var/folders/zc/6rc7nzhj13scy5qssxw2pjlh0000gn/T/ipykernel_21998/350309228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_kaggle_ventas.rename(columns={'Name':'game_name'}, inplace=True)

In [83]:
df_kaggle_ventas_2.rename(columns={'Name':'game_name'}, inplace=True)

In [42]:
df_kaggle_ventas

,Rank,game_name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [46]:
df_kaggle_ventas[df_kaggle_ventas['game_name'] == 'Grand Theft Auto V']

,Rank,game_name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
44,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
197,198,Grand Theft Auto V,XOne,2014.0,Action,Take-Two Interactive,2.66,2.01,0.00,0.41,5.08
1896,1898,Grand Theft Auto V,PC,2015.0,Action,Take-Two Interactive,0.36,0.64,0.00,0.08,1.08

In [70]:
df_suma = df_kaggle_ventas.groupby('game_name').agg({
    'NA_Sales': 'sum',
    'EU_Sales': 'sum',
    'JP_Sales': 'sum',
    'Other_Sales': 'sum',
    'Global_Sales': 'sum'
}).reset_index()

In [84]:
df_suma_2 = df_kaggle_ventas_2.groupby('game_name').agg({
    'NA_Sales': 'sum',
    'EU_Sales': 'sum',
    'JP_Sales': 'sum',
    'Other_Sales': 'sum',
    'Global_Sales': 'sum'
}).reset_index()

In [85]:
df_suma_2

,game_name,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,'98 Koshien,0.15,0.10,0.12,0.03,0.41
1,.hack//G.U. Vol.1//Rebirth,0.00,0.00,0.17,0.00,0.17
2,.hack//G.U. Vol.2//Reminisce,0.11,0.09,0.00,0.03,0.23
3,.hack//G.U. Vol.2//Reminisce (jp sales),0.00,0.00,0.16,0.00,0.16
4,.hack//G.U. Vol.3//Redemption,0.00,0.00,0.17,0.00,0.17
...,...,...,...,...,...,...
11320,thinkSMART FAMILY!,0.03,0.00,0.00,0.00,0.03
11321,thinkSMART: Chess for Kids,0.01,0.00,0.00,0.00,0.01
11322,uDraw Studio,1.67,0.58,0.00,0.20,2.46
11323,uDraw Studio: Instant Artist,0.09,0.10,0.00,0.02,0.21
11324,Â¡Shin Chan Flipa en colores!,0.00,0.00,0.14,0.00,0.14

In [75]:
df_suma

,game_name,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,'98 Koshien,0.15,0.10,0.12,0.03,0.41
1,.hack//G.U. Vol.1//Rebirth,0.00,0.00,0.17,0.00,0.17
2,.hack//G.U. Vol.2//Reminisce,0.11,0.09,0.00,0.03,0.23
3,.hack//G.U. Vol.2//Reminisce (jp sales),0.00,0.00,0.16,0.00,0.16
4,.hack//G.U. Vol.3//Redemption,0.00,0.00,0.17,0.00,0.17
...,...,...,...,...,...,...
11320,thinkSMART FAMILY!,0.03,0.00,0.00,0.00,0.03
11321,thinkSMART: Chess for Kids,0.01,0.00,0.00,0.00,0.01
11322,uDraw Studio,1.67,0.58,0.00,0.20,2.46
11323,uDraw Studio: Instant Artist,0.09,0.10,0.00,0.02,0.21
11324,Â¡Shin Chan Flipa en colores!,0.00,0.00,0.14,0.00,0.14

In [79]:
df_suma

,game_name,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,'98 Koshien,0.15,0.10,0.12,0.03,0.41
1,.hack//G.U. Vol.1//Rebirth,0.00,0.00,0.17,0.00,0.17
2,.hack//G.U. Vol.2//Reminisce,0.11,0.09,0.00,0.03,0.23
3,.hack//G.U. Vol.2//Reminisce (jp sales),0.00,0.00,0.16,0.00,0.16
4,.hack//G.U. Vol.3//Redemption,0.00,0.00,0.17,0.00,0.17
...,...,...,...,...,...,...
11320,thinkSMART FAMILY!,0.03,0.00,0.00,0.00,0.03
11321,thinkSMART: Chess for Kids,0.01,0.00,0.00,0.00,0.01
11322,uDraw Studio,1.67,0.58,0.00,0.20,2.46
11323,uDraw Studio: Instant Artist,0.09,0.10,0.00,0.02,0.21
11324,Â¡Shin Chan Flipa en colores!,0.00,0.00,0.14,0.00,0.14

In [76]:
df_suma_sales_todo = pd.merge(df_scores_todo,df_suma,on='game_name',how='inner')

In [77]:
df_suma_sales_todo

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,suggestions_count,numero_stores,average_percentage_good,average_percentage_intermediate,average_percentage_bad,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,434,5,10.0,50.0,40.0,23.46,23.04,1.39,8.03,55.92
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,...,677,5,30.0,60.0,10.0,1.82,2.89,0.21,0.72,5.64
2,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,...,602,4,50.0,40.0,10.0,8.73,7.66,0.35,2.54,19.28
3,14,2093,No Man's Sky,2016-08-09,False,Teen,Adventure,"Action, RPG, Simulation, Indie, Massively Mult...",5475.0,5,...,760,5,10.0,50.0,40.0,0.58,0.74,0.02,0.26,1.60
4,29,58813,Resident Evil 2,2019-01-25,False,Mature,Shooter,"Adventure, Action",1512.0,5,...,528,3,30.0,60.0,10.0,2.31,1.57,2.09,0.46,6.44
5,48,35561,Star Wars: Republic Commando,2005-03-01,False,Teen,Shooter,Action,2390.0,7,...,657,6,60.0,30.0,10.0,0.48,0.21,0.00,0.03,0.72
6,49,54491,Quake,1996-06-22,False,Mature,Shooter,Action,2436.0,13,...,471,5,50.0,30.0,20.0,0.15,0.04,0.00,0.00,0.19
7,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,581,3,40.0,60.0,0.0,4.87,4.54,0.21,1.44,11.08
8,485,52670,Ape Escape,1999-05-31,False,Everyone,Platformer,no,60.0,3,...,362,1,40.0,50.0,10.0,0.71,0.51,0.32,0.12,1.68
9,620,59315,Ace Combat 5: The Unsung War,2004-10-21,False,Mature,Simulation,no,16.0,3,...,119,0,60.0,20.0,20.0,0.88,0.34,0.32,0.18,1.71

In [86]:
df_suma_sales_todo_k_2 = pd.merge(df_scores_todo,df_suma_2,on='game_name',how='inner')

In [87]:
df_suma_sales_todo_k_2

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,suggestions_count,numero_stores,average_percentage_good,average_percentage_intermediate,average_percentage_bad,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,434,5,10.0,50.0,40.0,23.46,23.04,1.39,8.03,55.92
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,...,677,5,30.0,60.0,10.0,1.82,2.89,0.21,0.72,5.64
2,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,...,602,4,50.0,40.0,10.0,8.73,7.66,0.35,2.54,19.28
3,14,2093,No Man's Sky,2016-08-09,False,Teen,Adventure,"Action, RPG, Simulation, Indie, Massively Mult...",5475.0,5,...,760,5,10.0,50.0,40.0,0.58,0.74,0.02,0.26,1.60
4,29,58813,Resident Evil 2,2019-01-25,False,Mature,Shooter,"Adventure, Action",1512.0,5,...,528,3,30.0,60.0,10.0,2.31,1.57,2.09,0.46,6.44
5,48,35561,Star Wars: Republic Commando,2005-03-01,False,Teen,Shooter,Action,2390.0,7,...,657,6,60.0,30.0,10.0,0.48,0.21,0.00,0.03,0.72
6,49,54491,Quake,1996-06-22,False,Mature,Shooter,Action,2436.0,13,...,471,5,50.0,30.0,20.0,0.15,0.04,0.00,0.00,0.19
7,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,581,3,40.0,60.0,0.0,4.87,4.54,0.21,1.44,11.08
8,485,52670,Ape Escape,1999-05-31,False,Everyone,Platformer,no,60.0,3,...,362,1,40.0,50.0,10.0,0.71,0.51,0.32,0.12,1.68
9,620,59315,Ace Combat 5: The Unsung War,2004-10-21,False,Mature,Simulation,no,16.0,3,...,119,0,60.0,20.0,20.0,0.88,0.34,0.32,0.18,1.71

### df_s por plataforma

In [49]:
# Crear un diccionario para almacenar los DataFrames separados
dfs_por_plataforma = {platform: df_kaggle_ventas[df_kaggle_ventas['Platform'] == platform].reset_index(drop=True) 
                      for platform in df_kaggle_ventas['Platform'].unique()}

# Acceder a cada DataFrame por su plataforma
df_ps3 = dfs_por_plataforma['PS3']
df_x360 = dfs_por_plataforma['X360']
df_ps4 = dfs_por_plataforma['PS4']
df_xone = dfs_por_plataforma['XOne']
df_pc = dfs_por_plataforma['PC']
df_ps = dfs_por_plataforma['PS']

df_ps3

,Rank,game_name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
1,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
2,38,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.82,0.49,1.62,13.46
3,41,Call of Duty: Black Ops,PS3,2010.0,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
4,55,Gran Turismo 5,PS3,2010.0,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77
...,...,...,...,...,...,...,...,...,...,...,...
1299,16453,Hyperdimension Neptunia mk2,PS3,2011.0,Action,Nippon Ichi Software,0.00,0.01,0.00,0.00,0.01
1300,16454,Shin Koihime Musou: Otome Taisen * Sangokushi ...,PS3,2014.0,Adventure,Views,0.00,0.00,0.01,0.00,0.01
1301,16483,Muv-Luv Alternative,PS3,2012.0,Simulation,5pb,0.00,0.00,0.01,0.00,0.01
1302,16524,Akatsuki no Goei Trinity,PS3,2012.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01
1303,16544,Battle Fantasia,PS3,2008.0,Fighting,505 Games,0.00,0.00,0.01,0.00,0.01

In [66]:
df_ps = dfs_por_plataforma['PS']

In [68]:
df_merge_completo_ps = pd.merge(df_scores_todo, df_ps, on='game_name', how='inner')

In [69]:
df_merge_completo_ps

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,29,58813,Resident Evil 2,2019-01-25,False,Mature,Shooter,"Adventure, Action",1512.0,5,...,152,PS,1998.0,Action,Virgin Interactive,1.88,1.47,2.02,0.45,5.82
1,485,52670,Ape Escape,1999-05-31,False,Everyone,Platformer,no,60.0,3,...,1131,PS,1999.0,Platform,Sony Computer Entertainment,0.71,0.48,0.32,0.11,1.63

In [50]:
df_merge_completo_ps3 = pd.merge(df_scores_todo, df_ps3, on='game_name', how='inner')

In [51]:
df_merge_completo_ps3

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,17,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
1,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,...,127,PS3,2011.0,Role-Playing,Bethesda Softworks,2.55,2.71,0.25,1.05,6.56
2,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,828,PS3,2013.0,Role-Playing,Activision,0.71,0.83,0.15,0.35,2.05
3,485,52670,Ape Escape,1999-05-31,False,Everyone,Platformer,no,60.0,3,...,13439,PS3,2010.0,Platform,Sony Computer Entertainment,0.00,0.03,0.00,0.01,0.05

In [56]:
df_merge_completo_ps4 = pd.merge(df_scores_todo, df_ps4, on='game_name', how='inner')

In [57]:
df_merge_completo_ps4

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,45,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,...,332,PS4,2015.0,Role-Playing,Namco Bandai Games,0.96,2.00,0.21,0.56,3.73
2,14,2093,No Man's Sky,2016-08-09,False,Teen,Adventure,"Action, RPG, Simulation, Indie, Massively Mult...",5475.0,5,...,1158,PS4,2016.0,Action,Hello Games,0.58,0.74,0.02,0.26,1.60
3,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,1024,PS4,2014.0,Role-Playing,Activision,0.49,0.88,0.06,0.30,1.74

In [60]:
df_merge_completo_xOne = pd.merge(df_scores_todo, df_xone, on='game_name', how='inner')

In [61]:
df_merge_completo_xOne

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,198,XOne,2014.0,Action,Take-Two Interactive,2.66,2.01,0.0,0.41,5.08
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,...,1607,XOne,2015.0,Role-Playing,Namco Bandai Games,0.66,0.47,0.0,0.11,1.24
2,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,3138,XOne,2014.0,Role-Playing,Activision,0.35,0.24,0.0,0.05,0.64

In [62]:
df_merge_completo_pc = pd.merge(df_scores_todo, df_pc, on='game_name', how='inner')

In [63]:
df_merge_completo_pc

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,1898,PC,2015.0,Action,Take-Two Interactive,0.36,0.64,0.0,0.08,1.08
1,1,3328,The Witcher 3: Wild Hunt,2015-05-18,False,Mature,Action,RPG,12003.0,7,...,3028,PC,2015.0,Role-Playing,Namco Bandai Games,0.20,0.42,0.0,0.05,0.67
2,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,...,311,PC,2011.0,Role-Playing,Bethesda Softworks,1.15,2.09,0.0,0.64,3.88
3,48,35561,Star Wars: Republic Commando,2005-03-01,False,Teen,Shooter,Action,2390.0,7,...,13040,PC,2005.0,Shooter,LucasArts,0.00,0.04,0.0,0.01,0.05
4,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,182,PC,2012.0,Role-Playing,Activision,2.43,2.15,0.0,0.62,5.20

In [64]:
df_merge_completo_x360 = pd.merge(df_scores_todo, df_x360, on='game_name', how='inner')

In [65]:
df_merge_completo_x360

,Unnamed: 0,game_id,game_name,released,tba,age rating,genre,subgenre,owned,numero_plataformas,...,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,3498,Grand Theft Auto V,2013-09-17,False,Mature,Action,no,12151.0,7,...,24,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
1,2,5679,The Elder Scrolls V: Skyrim,2011-11-11,False,Mature,Action,RPG,9518.0,8,...,76,X360,2011.0,Role-Playing,Bethesda Softworks,5.03,2.86,0.10,0.85,8.84
2,76,23600,Diablo III,2012-05-15,False,Mature,Action,RPG,880.0,9,...,1318,X360,2013.0,Role-Playing,Activision,0.89,0.44,0.00,0.12,1.45